sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 219.223.251.96
    port: 3306
    database: sky_take_out
    username: yg
    password: 125125
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHwPGXAmeGMseEBuzpa
    access-key-secret: UzlVGGvCXvAn9Ww6kOlSdpb3dglIAX
    bucket-name: web-refuer
  redis:
    host: 219.223.251.96
    port: 6379
    password: 125125
    database: 10